-- 0140_01_cost_rate_DOWN.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- Not a migration. Paste into the SQL editor to undo the block.

-- block 01-cost-rate
ALTER TABLE "EMPLOYEE_COST_RATE" RENAME TO "EMPLOYEE_CP_RATE";
ALTER TABLE "EMPLOYEE_CP_RATE" RENAME COLUMN "COST_RATE" TO "CP_RATE";
ALTER TABLE "PROJECT_BOOKING_PRICE" RENAME COLUMN "COST_RATE" TO "CP_RATE";
ALTER TABLE "TEC" RENAME COLUMN "COST_RATE" TO "CP_RATE";
ALTER TABLE "TEC" RENAME COLUMN "COST_TOTAL" TO "CP_TOT";
ALTER TABLE "TEC_REBOOKING" RENAME COLUMN "COST_TOTAL" TO "CP_TOT";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
