-- 0144_03_role_name_DOWN.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- Not a migration. Paste into the SQL editor to undo the block.

-- block 03-role-name
ALTER TABLE "EMPLOYEE2PROJECT" RENAME COLUMN "ROLE_ABBR" TO "ROLE_NAME_SHORT";
ALTER TABLE "EMPLOYEE2PROJECT" RENAME COLUMN "ROLE_NAME" TO "ROLE_NAME_LONG";
ALTER TABLE "NACHTRAG_STRUCTURE" RENAME COLUMN "ROLE_ABBR" TO "ROLE_NAME_SHORT";
ALTER TABLE "NACHTRAG_STRUCTURE" RENAME COLUMN "ROLE_NAME" TO "ROLE_NAME_LONG";
ALTER TABLE "OFFER_STRUCTURE" RENAME COLUMN "ROLE_ABBR" TO "ROLE_NAME_SHORT";
ALTER TABLE "OFFER_STRUCTURE" RENAME COLUMN "ROLE_NAME" TO "ROLE_NAME_LONG";
ALTER TABLE "TEC" RENAME COLUMN "ROLE_ABBR" TO "ROLE_NAME_SHORT";
ALTER TABLE "TEC" RENAME COLUMN "ROLE_NAME" TO "ROLE_NAME_LONG";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
