-- 0145_04_employee_abbr_DOWN.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- Not a migration. Paste into the SQL editor to undo the block.

-- block 04-employee-abbr
ALTER TABLE "EMPLOYEE" RENAME COLUMN "ABBR" TO "SHORT_NAME";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
