-- 0150_05b_advance_invoice_rest_DOWN.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- Not a migration. Paste into the SQL editor to undo the block.

-- block 05b-advance-invoice-rest
ALTER TABLE "ADVANCE_INVOICE" RENAME COLUMN "CANCELS_ADVANCE_INVOICE_ID" TO "CANCELS_PARTIAL_PAYMENT_ID";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
