-- 0152_06_booking_DOWN.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- Not a migration. Paste into the SQL editor to undo the block.

-- block 06-booking
ALTER TABLE "ARBZG_AUDIT" RENAME COLUMN "BOOKING_DATE" TO "DATE_VOUCHER";
ALTER TABLE "ARBZG_AUDIT" RENAME COLUMN "BOOKING_ID" TO "TEC_ID";
ALTER TABLE "BOOKING" RENAME TO "TEC";
ALTER TABLE "TEC" RENAME COLUMN "BOOKING_DATE" TO "DATE_VOUCHER";
ALTER TABLE "BOOKING_REBOOKING" RENAME TO "TEC_REBOOKING";
ALTER TABLE "TEC_REBOOKING" RENAME COLUMN "BOOKING_DATE" TO "DATE_VOUCHER";
ALTER TABLE "TEC_REBOOKING" RENAME COLUMN "BOOKING_ID" TO "TEC_ID";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
