-- Add XRechnung XML snapshot fields to PARTIAL_PAYMENT

-- 1) Columns (safe to run multiple times)
ALTER TABLE "PARTIAL_PAYMENT"
  ADD COLUMN IF NOT EXISTS "DOCUMENT_XML_ASSET_ID" bigint NULL,
  ADD COLUMN IF NOT EXISTS "DOCUMENT_XML_PROFILE" text NULL,
  ADD COLUMN IF NOT EXISTS "DOCUMENT_XML_RENDERED_AT" timestamptz NULL;

-- 2) FK constraint (safe to run multiple times)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'PARTIAL_PAYMENT_DOCUMENT_XML_ASSET_ID_FK'
  ) THEN
    ALTER TABLE "PARTIAL_PAYMENT"
      ADD CONSTRAINT "PARTIAL_PAYMENT_DOCUMENT_XML_ASSET_ID_FK"
      FOREIGN KEY ("DOCUMENT_XML_ASSET_ID")
      REFERENCES "ASSET"("ID")
      ON DELETE SET NULL;
  END IF;
END $$;
