-- Link OFFER ↔ PROJECT for the "Beauftragt" conversion feature
ALTER TABLE OFFER    ADD COLUMN IF NOT EXISTS PROJECT_ID  INTEGER;
ALTER TABLE OFFER    ADD COLUMN IF NOT EXISTS ORDER_DATE  DATE;
ALTER TABLE PROJECT  ADD COLUMN IF NOT EXISTS OFFER_ID    INTEGER;
