-- Migration 0034: Employee month-close tracking
-- Run manually in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS "EMPLOYEE_MONTH_CLOSE" (
  "ID"          SERIAL PRIMARY KEY,
  "TENANT_ID"   INTEGER NOT NULL,
  "EMPLOYEE_ID" INTEGER NOT NULL,
  "YEAR"        INTEGER NOT NULL,
  "MONTH"       INTEGER NOT NULL,
  "CLOSED_AT"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "CLOSED_BY"   INTEGER NOT NULL,
  UNIQUE ("TENANT_ID", "EMPLOYEE_ID", "YEAR", "MONTH")
);

CREATE INDEX IF NOT EXISTS idx_emc_tenant_emp    ON "EMPLOYEE_MONTH_CLOSE"("TENANT_ID", "EMPLOYEE_ID");
CREATE INDEX IF NOT EXISTS idx_emc_tenant_period ON "EMPLOYEE_MONTH_CLOSE"("TENANT_ID", "YEAR", "MONTH");
