-- Migration 0034: Vollkostensatz-Rechner
-- Annual overhead cost items per tenant/year
CREATE TABLE IF NOT EXISTS "COST_RATE_CONFIG" (
  "ID"        SERIAL PRIMARY KEY,
  "TENANT_ID" INTEGER NOT NULL,
  "YEAR"      INTEGER NOT NULL,
  "CATEGORY"  TEXT NOT NULL DEFAULT 'Sonstiges',
  "ITEM_NAME" TEXT NOT NULL,
  "AMOUNT"    NUMERIC NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_crc ON "COST_RATE_CONFIG"("TENANT_ID","YEAR");

-- Per-employee calculation parameters per year
CREATE TABLE IF NOT EXISTS "COST_RATE_EMP_PARAMS" (
  "ID"                 SERIAL PRIMARY KEY,
  "TENANT_ID"          INTEGER NOT NULL,
  "EMPLOYEE_ID"        INTEGER NOT NULL,
  "YEAR"               INTEGER NOT NULL,
  "ANNUAL_SALARY"      NUMERIC NOT NULL DEFAULT 0,
  "WEEKLY_HOURS"       NUMERIC NOT NULL DEFAULT 40,
  "VACATION_DAYS"      NUMERIC NOT NULL DEFAULT 30,
  "SICK_DAYS_EST"      NUMERIC NOT NULL DEFAULT 7,
  "TRAINING_DAYS"      NUMERIC NOT NULL DEFAULT 5,
  "SOCIAL_CONTRIB_PCT" NUMERIC NOT NULL DEFAULT 21,
  "PRODUCTIVITY_PCT"   NUMERIC NOT NULL DEFAULT 85,
  UNIQUE("TENANT_ID","EMPLOYEE_ID","YEAR")
);
