-- Migration 0037: Mahnungswesen (Dunning Module)
-- Run manually in Supabase SQL editor

-- Core dunning state per invoice / partial payment
CREATE TABLE IF NOT EXISTS "MAHNUNG" (
  "ID"                      SERIAL PRIMARY KEY,
  "TENANT_ID"               INTEGER NOT NULL,
  "INVOICE_ID"              INTEGER REFERENCES "INVOICE"("ID") ON DELETE CASCADE,
  "PP_ID"                   INTEGER REFERENCES "PARTIAL_PAYMENT"("ID") ON DELETE CASCADE,
  "MAHNSTUFE"               INTEGER NOT NULL DEFAULT 0,
  "LAST_MAHNUNG_DATE"       DATE,
  "NEXT_MAHNUNG_DATE"       DATE,
  "RESPONSIBLE_EMPLOYEE_ID" INTEGER REFERENCES "EMPLOYEE"("ID"),
  "IS_CLOSED"               BOOLEAN NOT NULL DEFAULT FALSE,
  "CLOSE_REASON"            TEXT,
  "IN_KLAERUNG"             BOOLEAN NOT NULL DEFAULT FALSE,
  "NOTES"                   TEXT,
  "CREATED_AT"              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "UPDATED_AT"              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_mahnung_source CHECK (
    ("INVOICE_ID" IS NOT NULL AND "PP_ID" IS NULL) OR
    ("INVOICE_ID" IS NULL  AND "PP_ID" IS NOT NULL)
  ),
  CONSTRAINT uq_mahnung_invoice UNIQUE ("INVOICE_ID"),
  CONSTRAINT uq_mahnung_pp      UNIQUE ("PP_ID")
);

-- History log — one row per dunning action (level change or email send)
CREATE TABLE IF NOT EXISTS "MAHNUNG_HISTORY" (
  "ID"            SERIAL PRIMARY KEY,
  "TENANT_ID"     INTEGER NOT NULL,
  "MAHNUNG_ID"    INTEGER NOT NULL REFERENCES "MAHNUNG"("ID") ON DELETE CASCADE,
  "MAHNSTUFE"     INTEGER NOT NULL,
  "DATE_ACTION"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "EMPLOYEE_ID"   INTEGER REFERENCES "EMPLOYEE"("ID"),
  "EMAIL_TO"      TEXT,
  "EMAIL_SUBJECT" TEXT,
  "EMAIL_SENT"    BOOLEAN NOT NULL DEFAULT FALSE,
  "FEE_AMOUNT"    DECIMAL(12,4) NOT NULL DEFAULT 0,
  "NOTES"         TEXT
);

-- Per-tenant dunning level configuration (4 levels)
CREATE TABLE IF NOT EXISTS "MAHNUNG_SETTINGS" (
  "ID"              SERIAL PRIMARY KEY,
  "TENANT_ID"       INTEGER NOT NULL,
  "MAHNSTUFE"       INTEGER NOT NULL CHECK ("MAHNSTUFE" BETWEEN 1 AND 4),
  "LABEL"           TEXT    NOT NULL,
  "DAYS_AFTER_DUE"  INTEGER NOT NULL DEFAULT 7,
  "DAYS_AFTER_PREV" INTEGER NOT NULL DEFAULT 14,
  "FEE"             DECIMAL(10,2) NOT NULL DEFAULT 0,
  "HEADER_TEXT"     TEXT,
  "FOOTER_TEXT"     TEXT,
  UNIQUE ("TENANT_ID", "MAHNSTUFE")
);
