-- Migration: Add cumulative surcharge fields to PROJECT_STRUCTURE
-- Up to 3 named surcharges per structure node.
-- Calculation: bottom-up aggregation, each surcharge can be cumulative (on running subtotal) or additive (always on REVENUE+EXTRAS base).
-- SURCHARGES_TOTAL = own computed surcharges for THIS node only (not aggregated from children).

ALTER TABLE "PROJECT_STRUCTURE"
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  -- Sum of all three computed surcharge EUR amounts for this node
  ADD COLUMN IF NOT EXISTS "SURCHARGES_TOTAL"   DECIMAL(14,4) NOT NULL DEFAULT 0;
