-- 0040: Internal flag for projects and project structure elements
-- Run manually in Supabase SQL editor

ALTER TABLE "PROJECT"
  ADD COLUMN IF NOT EXISTS "IS_INTERNAL" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "PROJECT_STRUCTURE"
  ADD COLUMN IF NOT EXISTS "IS_INTERNAL" BOOLEAN NOT NULL DEFAULT FALSE;
