-- Migration 0041: Link PROJECT_STRUCTURE rows back to the HOAI calculation that created them
-- Enables syncing REVENUE back to structure when HOAI calculation is updated

ALTER TABLE "PROJECT_STRUCTURE"
  ADD COLUMN IF NOT EXISTS "FEE_CALC_MASTER_ID" INTEGER REFERENCES "FEE_CALCULATION_MASTER"("ID") ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "FEE_CALC_PHASE_ID"  INTEGER REFERENCES "FEE_CALCULATION_PHASE"("ID")  ON DELETE SET NULL;
