-- Besondere Leistungen per HOAI calculation
CREATE TABLE IF NOT EXISTS "FEE_CALCULATION_BL" (
  "ID"                  SERIAL PRIMARY KEY,
  "TENANT_ID"           INTEGER NOT NULL,
  "FEE_CALC_MASTER_ID"  INTEGER NOT NULL REFERENCES "FEE_CALCULATION_MASTER"("ID") ON DELETE CASCADE,
  "NAME"                TEXT NOT NULL,
  "LPH_REF"             TEXT DEFAULT NULL,
  "AMOUNT"              DECIMAL(14,4) NOT NULL DEFAULT 0,
  "SORT_ORDER"          INTEGER NOT NULL DEFAULT 0,
  "CREATED_AT"          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Allow surcharges to opt-in to include BL total in their base
ALTER TABLE "FEE_CALCULATION_SURCHARGES"
  ADD COLUMN IF NOT EXISTS "INCLUDE_BL" BOOLEAN NOT NULL DEFAULT FALSE;
