-- Migration 0043: Extend FEE_CALCULATION_BL with new fields and link PROJECT_STRUCTURE to BL items

ALTER TABLE "FEE_CALCULATION_BL"
  ADD COLUMN IF NOT EXISTS "NAME_SHORT"   TEXT,
  ADD COLUMN IF NOT EXISTS "LPH_PHASE_ID" INTEGER REFERENCES "FEE_CALCULATION_PHASE"("ID") ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "AMOUNT_TYPE"  TEXT NOT NULL DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS "PERCENT"      DECIMAL(10,4),
  ADD COLUMN IF NOT EXISTS "KX_REF"       TEXT;

ALTER TABLE "PROJECT_STRUCTURE"
  ADD COLUMN IF NOT EXISTS "FEE_CALC_BL_ID" INTEGER REFERENCES "FEE_CALCULATION_BL"("ID") ON DELETE SET NULL;
