-- Migration: Add surcharge fields + REVENUE_BASIS to OFFER_STRUCTURE
-- Mirrors the PROJECT_STRUCTURE surcharge migration (0039_project_structure_surcharges.sql)

ALTER TABLE "OFFER_STRUCTURE"
  ADD COLUMN IF NOT EXISTS "REVENUE_BASIS"       DECIMAL(14,4),

  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_LABEL"   TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_PCT"     DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_EUR"     DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_CUMUL"   BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_LABEL"   TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_PCT"     DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_EUR"     DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_CUMUL"   BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_LABEL"   TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_PCT"     DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_EUR"     DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_CUMUL"   BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGES_TOTAL"    DECIMAL(14,4) NOT NULL DEFAULT 0;

-- Backfill REVENUE_BASIS for existing rows (REVENUE = base, no surcharges yet)
UPDATE "OFFER_STRUCTURE" SET "REVENUE_BASIS" = "REVENUE" WHERE "REVENUE_BASIS" IS NULL;
