-- Migration: Add root-level surcharge columns to PROJECT and OFFER
-- Mirrors the PROJECT_STRUCTURE / OFFER_STRUCTURE surcharge schema but applied
-- at the root (project / offer) level. The user-entered base for these is the
-- sum of REVENUE across root structure nodes (FATHER_ID IS NULL).

ALTER TABLE "PROJECT"
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGES_TOTAL"   DECIMAL(14,4) NOT NULL DEFAULT 0;

ALTER TABLE "OFFER"
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_1_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_2_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_LABEL"  TEXT,
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_PCT"    DECIMAL(9,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_EUR"    DECIMAL(14,4),
  ADD COLUMN IF NOT EXISTS "SURCHARGE_3_CUMUL"  BOOLEAN NOT NULL DEFAULT TRUE,

  ADD COLUMN IF NOT EXISTS "SURCHARGES_TOTAL"   DECIMAL(14,4) NOT NULL DEFAULT 0;
