-- 0140_01_cost_rate.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- block 01-cost-rate
ALTER TABLE "EMPLOYEE_CP_RATE" RENAME COLUMN "CP_RATE" TO "COST_RATE";
ALTER TABLE "EMPLOYEE_CP_RATE" RENAME TO "EMPLOYEE_COST_RATE";
ALTER TABLE "PROJECT_BOOKING_PRICE" RENAME COLUMN "CP_RATE" TO "COST_RATE";
ALTER TABLE "TEC" RENAME COLUMN "CP_RATE" TO "COST_RATE";
ALTER TABLE "TEC" RENAME COLUMN "CP_TOT" TO "COST_TOTAL";
ALTER TABLE "TEC_REBOOKING" RENAME COLUMN "CP_TOT" TO "COST_TOTAL";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
