-- 0144_03_role_name.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- block 03-role-name
ALTER TABLE "EMPLOYEE2PROJECT" RENAME COLUMN "ROLE_NAME_SHORT" TO "ROLE_ABBR";
ALTER TABLE "EMPLOYEE2PROJECT" RENAME COLUMN "ROLE_NAME_LONG" TO "ROLE_NAME";
ALTER TABLE "NACHTRAG_STRUCTURE" RENAME COLUMN "ROLE_NAME_SHORT" TO "ROLE_ABBR";
ALTER TABLE "NACHTRAG_STRUCTURE" RENAME COLUMN "ROLE_NAME_LONG" TO "ROLE_NAME";
ALTER TABLE "OFFER_STRUCTURE" RENAME COLUMN "ROLE_NAME_SHORT" TO "ROLE_ABBR";
ALTER TABLE "OFFER_STRUCTURE" RENAME COLUMN "ROLE_NAME_LONG" TO "ROLE_NAME";
ALTER TABLE "TEC" RENAME COLUMN "ROLE_NAME_SHORT" TO "ROLE_ABBR";
ALTER TABLE "TEC" RENAME COLUMN "ROLE_NAME_LONG" TO "ROLE_NAME";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
