-- 0145_04_employee_abbr.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- block 04-employee-abbr
ALTER TABLE "EMPLOYEE" RENAME COLUMN "SHORT_NAME" TO "ABBR";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
