-- Generated by backend/scripts/rename/rename.js functions - READ BEFORE APPLYING.
-- Source of truth: backend/scripts/rename/rename-map.json
--
-- ALTER ... RENAME leaves plpgsql bodies and view output columns alone. This
-- file is that leftover, with the same replacement applied that the codemod
-- applied to the JS. It is generated, not authored - but it is NOT automatic:
--
--   * a "table"-scoped identifier was replaced everywhere it appeared here.
--     If a body also reads a table that keeps the old column, that line is
--     now wrong. Check each one.
--   * CREATE VIEW loses an explicit column list, if the original had one.
--   * apply this AFTER the ALTER migration, in the same deploy.

-- Views, most dependent first. They come down so their output column
-- names can change - CREATE OR REPLACE VIEW cannot rename a column.
DROP VIEW IF EXISTS "public"."VW_REPORT_PROJECT_LIST_ROOT";
DROP VIEW IF EXISTS "public"."VW_REPORT_PROJECT_DETAIL";
DROP VIEW IF EXISTS "REPORTING"."VW_PROJECT_BILLING_AGG";

-- Functions. CREATE OR REPLACE keeps the OID, so grants survive.
CREATE OR REPLACE FUNCTION public.fn_project_report_header(p_tenant_id bigint, p_project_id bigint, p_as_of timestamp with time zone DEFAULT NULL::timestamp with time zone, p_date_from date DEFAULT NULL::date, p_date_to date DEFAULT NULL::date)
 RETURNS TABLE("TENANT_ID" bigint, "PROJECT_ID" bigint, "NAME_SHORT" text, "NAME_LONG" text, "PROJECT_STATUS_NAME_SHORT" text, "PROJECT_MANAGER_DISPLAY" text, "COMPANY_NAME" text, "BUDGET_TOTAL_NET" numeric, "LEISTUNGSSTAND_PERCENT" numeric, "LEISTUNGSSTAND_VALUE" numeric, "HOURS_TOTAL" numeric, "COST_TOTAL" numeric, "EARNED_VALUE_NET" numeric, "COST_RATIO" numeric, "REMAINING_BUDGET_NET" numeric, "ADVANCE_INVOICE_NET_TOTAL" numeric, "INVOICE_NET_TOTAL" numeric, "BILLED_NET_TOTAL" numeric, "OPEN_NET_TOTAL" numeric, "PAYED_NET_TOTAL" numeric, "SALES_TOTAL" numeric, "QTY_EXT_TOTAL" numeric)
 LANGUAGE sql
 STABLE
AS $function$
  WITH
    cutoff AS (
      SELECT
        CASE
          WHEN p_as_of   IS NOT NULL THEN p_as_of
          WHEN p_date_to IS NOT NULL THEN (p_date_to::timestamptz + INTERVAL '1 day' - INTERVAL '1 microsecond')
          ELSE now()
        END AS ts
    ),

    leaf_structs AS (
      SELECT
        ps."ID"              AS "STRUCTURE_ID",
        ps."BILLING_TYPE_ID",
        ps."REVENUE"         AS "REV_FALLBACK",
        ps."EXTRAS"          AS "EXT_FALLBACK",
        ps."created_at"      AS "CREATED_AT"
      FROM public."PROJECT_STRUCTURE" ps
      WHERE ps."TENANT_ID"  = p_tenant_id
        AND ps."PROJECT_ID" = p_project_id
        AND NOT EXISTS (
          SELECT 1 FROM public."PROJECT_STRUCTURE" child
          WHERE  child."TENANT_ID" = ps."TENANT_ID"
            AND  child."FATHER_ID" = ps."ID"
        )
    ),

    budget AS (
      SELECT
        ls."STRUCTURE_ID",
        ls."BILLING_TYPE_ID",
        COALESCE(
          pp_bud."REVENUE",
          CASE WHEN ls."CREATED_AT" <= c.ts THEN ls."REV_FALLBACK" END,
          0
        ) AS "REVENUE",
        COALESCE(
          pp_bud."EXTRAS",
          CASE WHEN ls."CREATED_AT" <= c.ts THEN ls."EXT_FALLBACK" END,
          0
        ) AS "EXTRAS"
      FROM leaf_structs ls
      CROSS JOIN cutoff c
      LEFT JOIN LATERAL (
        SELECT pp."REVENUE", pp."EXTRAS"
        FROM   public."PROJECT_PROGRESS" pp
        WHERE  pp."STRUCTURE_ID" = ls."STRUCTURE_ID"
          AND  pp."TENANT_ID"    = p_tenant_id
          AND  pp."REVENUE"      IS NOT NULL
          AND  pp."created_at"  <= c.ts
        ORDER  BY pp."created_at" DESC, pp."ID" DESC
        LIMIT  1
      ) pp_bud ON true
    ),

    completion AS (
      SELECT
        ls."STRUCTURE_ID",
        COALESCE(pp_compl."REVENUE_COMPLETION", 0) AS "REVENUE_COMPLETION",
        COALESCE(pp_compl."EXTRAS_COMPLETION",  0) AS "EXTRAS_COMPLETION"
      FROM leaf_structs ls
      CROSS JOIN cutoff c
      LEFT JOIN LATERAL (
        SELECT pp."REVENUE_COMPLETION", pp."EXTRAS_COMPLETION"
        FROM   public."PROJECT_PROGRESS" pp
        WHERE  pp."STRUCTURE_ID"      = ls."STRUCTURE_ID"
          AND  pp."TENANT_ID"         = p_tenant_id
          AND  pp."REVENUE_COMPLETION" IS NOT NULL
          AND  pp."created_at"        <= c.ts
        ORDER  BY pp."created_at" DESC, pp."ID" DESC
        LIMIT  1
      ) pp_compl ON true
      WHERE ls."BILLING_TYPE_ID" <> 2
    ),

    tec_leaf AS (
      SELECT
        t."STRUCTURE_ID",
        COALESCE(SUM(t."QUANTITY_INT"), 0) AS "HOURS_TOTAL",
        COALESCE(SUM(t."COST_TOTAL"),       0) AS "COST_TOTAL",
        COALESCE(SUM(t."HOURLY_RATE_TOTAL"),       0) AS "HOURLY_RATE_TOTAL",
        COALESCE(SUM(t."QUANTITY_EXT"), 0) AS "QTY_EXT_TOTAL"
      FROM public."TEC" t
      WHERE t."TENANT_ID"    = p_tenant_id
        AND t."STRUCTURE_ID" IN (SELECT "STRUCTURE_ID" FROM leaf_structs)
        AND (p_as_of     IS NULL OR t."DATE_VOUCHER" <= p_as_of::date)
        AND (p_date_from IS NULL OR t."DATE_VOUCHER" >= p_date_from)
        AND (p_date_to   IS NULL OR t."DATE_VOUCHER" <= p_date_to)
      GROUP BY t."STRUCTURE_ID"
    ),

    -- For BT2: Honorar = HOURLY_RATE_TOTAL (not budgeted REVENUE), so budget denominator uses HOURLY_RATE_TOTAL
    prog_agg AS (
      SELECT
        -- BT2: budget IS HOURLY_RATE_TOTAL (hourly: what was billed = the honorar)
        COALESCE(SUM(
          CASE WHEN b."BILLING_TYPE_ID" = 2
               THEN COALESCE(tl."HOURLY_RATE_TOTAL", 0)
               ELSE COALESCE(b."REVENUE", 0)
          END
        ), 0) AS "REVENUE_BUDGET",
        COALESCE(SUM(
          CASE WHEN b."BILLING_TYPE_ID" = 2 THEN 0
               ELSE COALESCE(b."EXTRAS", 0)
          END
        ), 0) AS "EXTRAS_BUDGET",
        -- earned value: BT2 = HOURLY_RATE_TOTAL, BT1 = recorded completion
        COALESCE(SUM(
          CASE WHEN b."BILLING_TYPE_ID" = 2
               THEN COALESCE(tl."HOURLY_RATE_TOTAL", 0)
               ELSE COALESCE(c."REVENUE_COMPLETION", 0)
          END
        ), 0) AS "REVENUE_COMPLETION_VALUE",
        COALESCE(SUM(
          CASE WHEN b."BILLING_TYPE_ID" = 2 THEN 0
               ELSE COALESCE(c."EXTRAS_COMPLETION", 0)
          END
        ), 0) AS "EXTRAS_COMPLETION_VALUE",
        -- LEISTUNGSSTAND_PERCENT: BT2 numerator = HOURLY_RATE_TOTAL, denominator = HOURLY_RATE_TOTAL → always 100%
        CASE
          WHEN SUM(
            CASE WHEN b."BILLING_TYPE_ID" = 2
                 THEN COALESCE(tl."HOURLY_RATE_TOTAL", 0)
                 ELSE COALESCE(b."REVENUE", 0) + COALESCE(b."EXTRAS", 0)
            END
          ) = 0 THEN NULL
          ELSE 100.0
             * SUM(
                 CASE WHEN b."BILLING_TYPE_ID" = 2 THEN COALESCE(tl."HOURLY_RATE_TOTAL", 0)
                      ELSE COALESCE(c."REVENUE_COMPLETION", 0)
                 END
               + CASE WHEN b."BILLING_TYPE_ID" = 2 THEN 0
                      ELSE COALESCE(c."EXTRAS_COMPLETION", 0)
                 END
               )
             / SUM(
                 CASE WHEN b."BILLING_TYPE_ID" = 2
                      THEN COALESCE(tl."HOURLY_RATE_TOTAL", 0)
                      ELSE COALESCE(b."REVENUE", 0) + COALESCE(b."EXTRAS", 0)
                 END
               )
        END AS "LEISTUNGSSTAND_PERCENT"
      FROM budget b
      LEFT JOIN completion c  ON  c."STRUCTURE_ID" = b."STRUCTURE_ID"
      LEFT JOIN tec_leaf   tl ON tl."STRUCTURE_ID" = b."STRUCTURE_ID"
    ),

    tec_agg AS (
      SELECT
        COALESCE(SUM(tl."HOURS_TOTAL"),   0) AS "HOURS_TOTAL",
        COALESCE(SUM(tl."COST_TOTAL"),    0) AS "COST_TOTAL",
        COALESCE(SUM(tl."HOURLY_RATE_TOTAL"),        0) AS "SALES_TOTAL",
        COALESCE(SUM(tl."QTY_EXT_TOTAL"), 0) AS "QTY_EXT_TOTAL"
      FROM tec_leaf tl
    ),

    pp_billed AS (
      SELECT COALESCE(SUM(pp."AMOUNT_NET" + COALESCE(pp."AMOUNT_EXTRAS_NET", 0)), 0) AS "PP_NET"
      FROM public."ADVANCE_INVOICE" pp
      WHERE pp."TENANT_ID"  = p_tenant_id
        AND pp."PROJECT_ID" = p_project_id
        AND pp."STATUS_ID"  = 2
        AND (p_as_of     IS NULL OR pp."ADVANCE_INVOICE_DATE" <= p_as_of::date)
        AND (p_date_from IS NULL OR pp."ADVANCE_INVOICE_DATE" >= p_date_from)
        AND (p_date_to   IS NULL OR pp."ADVANCE_INVOICE_DATE" <= p_date_to)
    ),
    inv_billed AS (
      SELECT COALESCE(SUM(inv."TOTAL_AMOUNT_NET"), 0) AS "INV_NET"
      FROM public."INVOICE" inv
      WHERE inv."TENANT_ID"  = p_tenant_id
        AND inv."PROJECT_ID" = p_project_id
        AND inv."STATUS_ID"  = 2
        AND (p_as_of     IS NULL OR inv."INVOICE_DATE" <= p_as_of::date)
        AND (p_date_from IS NULL OR inv."INVOICE_DATE" >= p_date_from)
        AND (p_date_to   IS NULL OR inv."INVOICE_DATE" <= p_date_to)
    ),

    pay_agg AS (
      SELECT COALESCE(SUM(pay."AMOUNT_PAYED_NET"), 0) AS "PAYED_NET_TOTAL"
      FROM public."PAYMENT" pay
      WHERE pay."TENANT_ID"  = p_tenant_id
        AND pay."PROJECT_ID" = p_project_id
        AND (p_as_of     IS NULL OR pay."PAYMENT_DATE" <= p_as_of::date)
        AND (p_date_from IS NULL OR pay."PAYMENT_DATE" >= p_date_from)
        AND (p_date_to   IS NULL OR pay."PAYMENT_DATE" <= p_date_to)
    )

  SELECT
    proj."TENANT_ID",
    proj."ID"::bigint,
    proj."NAME_SHORT",
    proj."NAME_LONG",
    ps_lkp."NAME_SHORT"   AS "PROJECT_STATUS_NAME_SHORT",
    ( e."ABBR" ||
      CASE WHEN e."FIRST_NAME" IS NOT NULL
           THEN ': ' || e."FIRST_NAME" || ' ' || COALESCE(e."LAST_NAME", '')
           ELSE '' END
    )                     AS "PROJECT_MANAGER_DISPLAY",
    c."COMPANY_NAME_1"    AS "COMPANY_NAME",

    pa."REVENUE_BUDGET" + pa."EXTRAS_BUDGET"                          AS "BUDGET_TOTAL_NET",
    pa."LEISTUNGSSTAND_PERCENT",
    pa."REVENUE_COMPLETION_VALUE" + pa."EXTRAS_COMPLETION_VALUE"      AS "LEISTUNGSSTAND_VALUE",
    ta."HOURS_TOTAL",
    ta."COST_TOTAL",
    pa."REVENUE_COMPLETION_VALUE" + pa."EXTRAS_COMPLETION_VALUE"      AS "EARNED_VALUE_NET",
    CASE
      WHEN (pa."REVENUE_COMPLETION_VALUE" + pa."EXTRAS_COMPLETION_VALUE") = 0 THEN NULL
      ELSE ta."COST_TOTAL" / (pa."REVENUE_COMPLETION_VALUE" + pa."EXTRAS_COMPLETION_VALUE")
    END                   AS "COST_RATIO",
    (pa."REVENUE_BUDGET" + pa."EXTRAS_BUDGET")
    - (pa."REVENUE_COMPLETION_VALUE" + pa."EXTRAS_COMPLETION_VALUE")  AS "REMAINING_BUDGET_NET",
    ppb."PP_NET"                    AS "ADVANCE_INVOICE_NET_TOTAL",
    ivb."INV_NET"                   AS "INVOICE_NET_TOTAL",
    ppb."PP_NET" + ivb."INV_NET"    AS "BILLED_NET_TOTAL",
    (pa."REVENUE_COMPLETION_VALUE" + pa."EXTRAS_COMPLETION_VALUE")
    - (ppb."PP_NET" + ivb."INV_NET") AS "OPEN_NET_TOTAL",
    pya."PAYED_NET_TOTAL",
    ta."SALES_TOTAL",
    ta."QTY_EXT_TOTAL"

  FROM public."PROJECT" proj
  CROSS JOIN prog_agg pa
  CROSS JOIN tec_agg  ta
  CROSS JOIN pp_billed ppb
  CROSS JOIN inv_billed ivb
  CROSS JOIN pay_agg  pya
  LEFT JOIN public."PROJECT_STATUS" ps_lkp ON ps_lkp."ID" = proj."PROJECT_STATUS_ID"
  LEFT JOIN public."EMPLOYEE" e
    ON  e."TENANT_ID" = proj."TENANT_ID"
   AND  e."ID"        = proj."PROJECT_MANAGER_ID"
  LEFT JOIN public."COMPANY" c
    ON  c."TENANT_ID" = proj."TENANT_ID"
   AND  c."ID"        = proj."COMPANY_ID"
  WHERE proj."TENANT_ID" = p_tenant_id
    AND proj."ID"        = p_project_id
$function$;

CREATE OR REPLACE FUNCTION public."FN_REPORT_PROJECT_DETAIL"(p_tenant_id bigint, p_project_id bigint, p_as_of timestamp with time zone DEFAULT NULL::timestamp with time zone, p_date_from date DEFAULT NULL::date, p_date_to date DEFAULT NULL::date)
 RETURNS TABLE("TENANT_ID" bigint, "PROJECT_ID" bigint, "NAME_SHORT" text, "NAME_LONG" text, "PROJECT_STATUS_ID" bigint, "PROJECT_STATUS_NAME_SHORT" text, "PROJECT_TYPE_ID" bigint, "PROJECT_TYPE_NAME_SHORT" text, "PROJECT_MANAGER_ID" bigint, "PROJECT_MANAGER_DISPLAY" text, "ADDRESS_ID" bigint, "ADDRESS_NAME" text, "COMPANY_ID" bigint, "COMPANY_NAME" text, "DEPARTMENT_ID" bigint, "DEPARTMENT_NAME" text, "CONTACT_ID" bigint, "CONTACT_NAME" text, "BUDGET_TOTAL_NET" numeric, "LEISTUNGSSTAND_PERCENT" numeric, "LEISTUNGSSTAND_VALUE" numeric, "HOURS_TOTAL" numeric, "COST_TOTAL" numeric, "DECKUNGSBEITRAG" numeric, "PROGNOSE_KOSTEN" numeric, "PROGNOSE_DECKUNGSBEITRAG" numeric, "ADVANCE_INVOICE_NET_TOTAL" numeric, "INVOICE_NET_TOTAL" numeric, "PAYED_NET_TOTAL" numeric, "BILLED_NET_TOTAL" numeric, "OPEN_NET_TOTAL" numeric, "ABRECHENBAR_NET" numeric)
 LANGUAGE sql
 STABLE
AS $function$
  select *
  from "REPORTING"."FN_REPORT_PROJECT_DETAIL"(
    p_tenant_id,
    p_project_id,
    p_as_of,
    p_date_from,
    p_date_to
  );
$function$;

CREATE OR REPLACE FUNCTION "REPORTING"."FN_REPORT_PROJECT_DETAIL"(p_tenant_id bigint, p_project_id bigint, p_as_of timestamp with time zone, p_date_from date, p_date_to date)
 RETURNS TABLE("TENANT_ID" bigint, "PROJECT_ID" bigint, "NAME_SHORT" text, "NAME_LONG" text, "PROJECT_STATUS_ID" bigint, "PROJECT_STATUS_NAME_SHORT" text, "PROJECT_TYPE_ID" bigint, "PROJECT_TYPE_NAME_SHORT" text, "PROJECT_MANAGER_ID" bigint, "PROJECT_MANAGER_DISPLAY" text, "ADDRESS_ID" bigint, "ADDRESS_NAME" text, "COMPANY_ID" bigint, "COMPANY_NAME" text, "DEPARTMENT_ID" bigint, "DEPARTMENT_NAME" text, "CONTACT_ID" bigint, "CONTACT_NAME" text, "BUDGET_TOTAL_NET" numeric, "LEISTUNGSSTAND_PERCENT" numeric, "LEISTUNGSSTAND_VALUE" numeric, "HOURS_TOTAL" numeric, "COST_TOTAL" numeric, "DECKUNGSBEITRAG" numeric, "PROGNOSE_KOSTEN" numeric, "PROGNOSE_DECKUNGSBEITRAG" numeric, "ADVANCE_INVOICE_NET_TOTAL" numeric, "INVOICE_NET_TOTAL" numeric, "PAYED_NET_TOTAL" numeric, "BILLED_NET_TOTAL" numeric, "OPEN_NET_TOTAL" numeric, "ABRECHENBAR_NET" numeric)
 LANGUAGE sql
 STABLE
AS $function$
with params as (
  select
    coalesce(p_as_of, now()) as as_of_ts,
    p_date_from as date_from,
    p_date_to as date_to
),

-- existing progress logic (as-of on created_at)
progress_latest as (
  select distinct on (pp."TENANT_ID", pp."STRUCTURE_ID")
    pp."TENANT_ID",
    pp."STRUCTURE_ID",
    pp."REVENUE",
    pp."EXTRAS",
    pp."REVENUE_COMPLETION_PERCENT",
    pp."REVENUE_COMPLETION",
    pp."EXTRAS_COMPLETION",
    pp."created_at",
    pp."ID" as "PROJECT_PROGRESS_ID"
  from public."PROJECT_PROGRESS" pp
  cross join params
  where pp."TENANT_ID" = p_tenant_id
    and pp."created_at" <= params.as_of_ts
  order by
    pp."TENANT_ID", pp."STRUCTURE_ID",
    pp."created_at" desc,
    pp."ID" desc
),

progress_agg as (
  select
    ps."TENANT_ID",
    ps."PROJECT_ID",
    sum(coalesce(pl."REVENUE",0)) as "REVENUE_BUDGET",
    sum(coalesce(pl."EXTRAS",0))  as "EXTRAS_BUDGET",
    avg(nullif(pl."REVENUE_COMPLETION_PERCENT",0)) as "REVENUE_COMPLETION_PERCENT_AVG",
    sum(coalesce(pl."REVENUE_COMPLETION",0)) as "REVENUE_COMPLETION_VALUE",
    sum(coalesce(pl."EXTRAS_COMPLETION",0))  as "EXTRAS_COMPLETION_VALUE"
  from progress_latest pl
  join public."PROJECT_STRUCTURE" ps
    on ps."TENANT_ID" = pl."TENANT_ID"
   and ps."ID"        = pl."STRUCTURE_ID"
  where ps."PROJECT_ID" = p_project_id
  group by ps."TENANT_ID", ps."PROJECT_ID"
),

/* ✅ FIXED: TEC now respects period OR as-of */
time_agg as (
  select
    ps."TENANT_ID",
    ps."PROJECT_ID",
    sum(coalesce(t."QUANTITY_INT",0)) as "HOURS_TOTAL",
    sum(coalesce(t."COST_TOTAL",0))       as "COST_TOTAL"
  from public."TEC" t
  join public."PROJECT_STRUCTURE" ps
    on ps."TENANT_ID" = t."TENANT_ID"
   and ps."ID"        = t."STRUCTURE_ID"
  cross join params
  where ps."TENANT_ID" = p_tenant_id
    and ps."PROJECT_ID" = p_project_id
    and (
      -- period mode has priority if any bound is provided
      (
        (params.date_from is not null or params.date_to is not null)
        and (params.date_from is null or t."DATE_VOUCHER"::date >= params.date_from)
        and (params.date_to   is null or t."DATE_VOUCHER"::date <= params.date_to)
      )
      or
      -- otherwise stichtag/as-of mode
      (
        params.date_from is null and params.date_to is null
        and t."DATE_VOUCHER"::date <= params.as_of_ts::date
      )
    )
  group by ps."TENANT_ID", ps."PROJECT_ID"
),

/* ✅ FIXED: PP/Invoice/Payment now also respect period OR as-of */
billing_agg as (
  select
    p."TENANT_ID",
    p."ID" as "PROJECT_ID",

    coalesce((
      select sum(coalesce(pp."TOTAL_AMOUNT_NET",0))
      from public."ADVANCE_INVOICE" pp
      cross join params
      where pp."TENANT_ID"  = p."TENANT_ID"
        and pp."PROJECT_ID" = p."ID"
        and (
          (
            (params.date_from is not null or params.date_to is not null)
            and (params.date_from is null or pp."ADVANCE_INVOICE_DATE"::date >= params.date_from)
            and (params.date_to   is null or pp."ADVANCE_INVOICE_DATE"::date <= params.date_to)
          )
          or
          (
            params.date_from is null and params.date_to is null
            and pp."ADVANCE_INVOICE_DATE"::date <= params.as_of_ts::date
          )
        )
    ),0) as "ADVANCE_INVOICE_NET_TOTAL",

    coalesce((
      select sum(coalesce(i."TOTAL_AMOUNT_NET",0))
      from public."INVOICE" i
      cross join params
      where i."TENANT_ID"   = p."TENANT_ID"
        and i."PROJECT_ID"  = p."ID"
        and (
          (
            (params.date_from is not null or params.date_to is not null)
            and (params.date_from is null or i."INVOICE_DATE"::date >= params.date_from)
            and (params.date_to   is null or i."INVOICE_DATE"::date <= params.date_to)
          )
          or
          (
            params.date_from is null and params.date_to is null
            and i."INVOICE_DATE"::date <= params.as_of_ts::date
          )
        )
    ),0) as "INVOICE_NET_TOTAL",

    coalesce((
      select sum(coalesce(pay."AMOUNT_PAYED_NET",0))
      from public."PAYMENT" pay
      cross join params
      where pay."TENANT_ID"  = p."TENANT_ID"
        and pay."PROJECT_ID" = p."ID"
        and (
          (
            (params.date_from is not null or params.date_to is not null)
            and (params.date_from is null or pay."PAYMENT_DATE"::date >= params.date_from)
            and (params.date_to   is null or pay."PAYMENT_DATE"::date <= params.date_to)
          )
          or
          (
            params.date_from is null and params.date_to is null
            and pay."PAYMENT_DATE"::date <= params.as_of_ts::date
          )
        )
    ),0) as "PAYED_NET_TOTAL"

  from public."PROJECT" p
  where p."TENANT_ID" = p_tenant_id
    and p."ID"        = p_project_id
)

select
  p."TENANT_ID",
  p."ID" as "PROJECT_ID",
  p."NAME_SHORT",
  p."NAME_LONG",

  p."PROJECT_STATUS_ID",
  ps."NAME_SHORT" as "PROJECT_STATUS_NAME_SHORT",
  p."PROJECT_TYPE_ID",
  pt."NAME_SHORT" as "PROJECT_TYPE_NAME_SHORT",
  p."PROJECT_MANAGER_ID",
  (e."ABBR" || case when e."FIRST_NAME" is not null then (': ' || e."FIRST_NAME" || ' ' || coalesce(e."LAST_NAME",'')) else '' end)
    as "PROJECT_MANAGER_DISPLAY",

  p."ADDRESS_ID",
  a."ADDRESS_NAME_1" as "ADDRESS_NAME",
  p."COMPANY_ID",
  c."COMPANY_NAME_1" as "COMPANY_NAME",
  p."DEPARTMENT_ID",
  d."NAME_SHORT" as "DEPARTMENT_NAME",
  p."CONTACT_ID",
  co."LAST_NAME" as "CONTACT_NAME",

  (coalesce(pa."REVENUE_BUDGET",0) + coalesce(pa."EXTRAS_BUDGET",0)) as "BUDGET_TOTAL_NET",
  coalesce(pa."REVENUE_COMPLETION_PERCENT_AVG", null) as "LEISTUNGSSTAND_PERCENT",
  (coalesce(pa."REVENUE_COMPLETION_VALUE",0) + coalesce(pa."EXTRAS_COMPLETION_VALUE",0)) as "LEISTUNGSSTAND_VALUE",
  coalesce(ta."HOURS_TOTAL",0) as "HOURS_TOTAL",
  coalesce(ta."COST_TOTAL",0)  as "COST_TOTAL",

  ((coalesce(pa."REVENUE_COMPLETION_VALUE",0) + coalesce(pa."EXTRAS_COMPLETION_VALUE",0)) - coalesce(ta."COST_TOTAL",0)) as "DECKUNGSBEITRAG",

  case
    when coalesce(pa."REVENUE_COMPLETION_PERCENT_AVG",0) = 0 then null
    else coalesce(ta."COST_TOTAL",0) / (coalesce(pa."REVENUE_COMPLETION_PERCENT_AVG",0) / 100.0)
  end as "PROGNOSE_KOSTEN",

  case
    when coalesce(pa."REVENUE_COMPLETION_PERCENT_AVG",0) = 0 then null
    else (coalesce(pa."REVENUE_BUDGET",0) + coalesce(pa."EXTRAS_BUDGET",0))
         - (coalesce(ta."COST_TOTAL",0) / (coalesce(pa."REVENUE_COMPLETION_PERCENT_AVG",0) / 100.0))
  end as "PROGNOSE_DECKUNGSBEITRAG",

  coalesce(ba."ADVANCE_INVOICE_NET_TOTAL",0) as "ADVANCE_INVOICE_NET_TOTAL",
  coalesce(ba."INVOICE_NET_TOTAL",0)         as "INVOICE_NET_TOTAL",
  coalesce(ba."PAYED_NET_TOTAL",0)           as "PAYED_NET_TOTAL",
  (coalesce(ba."ADVANCE_INVOICE_NET_TOTAL",0) + coalesce(ba."INVOICE_NET_TOTAL",0)) as "BILLED_NET_TOTAL",
  (coalesce(ba."ADVANCE_INVOICE_NET_TOTAL",0) + coalesce(ba."INVOICE_NET_TOTAL",0) - coalesce(ba."PAYED_NET_TOTAL",0)) as "OPEN_NET_TOTAL",
  ((coalesce(pa."REVENUE_COMPLETION_VALUE",0) + coalesce(pa."EXTRAS_COMPLETION_VALUE",0))
    - (coalesce(ba."ADVANCE_INVOICE_NET_TOTAL",0) + coalesce(ba."INVOICE_NET_TOTAL",0))) as "ABRECHENBAR_NET"

from public."PROJECT" p
left join progress_agg pa on pa."TENANT_ID" = p."TENANT_ID" and pa."PROJECT_ID" = p."ID"
left join time_agg ta     on ta."TENANT_ID" = p."TENANT_ID" and ta."PROJECT_ID" = p."ID"
left join billing_agg ba  on ba."TENANT_ID" = p."TENANT_ID" and ba."PROJECT_ID" = p."ID"
left join public."EMPLOYEE" e on e."TENANT_ID" = p."TENANT_ID" and e."ID" = p."PROJECT_MANAGER_ID"
left join public."PROJECT_STATUS" ps on ps."ID" = p."PROJECT_STATUS_ID"
left join public."PROJECT_TYPE" pt on pt."ID" = p."PROJECT_TYPE_ID"
left join public."ADDRESS" a on a."TENANT_ID" = p."TENANT_ID" and a."ID" = p."ADDRESS_ID"
left join public."COMPANY" c on c."TENANT_ID" = p."TENANT_ID" and c."ID" = p."COMPANY_ID"
left join public."DEPARTMENT" d on d."TENANT_ID" = p."TENANT_ID" and d."ID" = p."DEPARTMENT_ID"
left join public."CONTACTS" co on co."TENANT_ID" = p."TENANT_ID" and co."ID" = p."CONTACT_ID"
where p."TENANT_ID" = p_tenant_id
  and p."ID"        = p_project_id;
$function$;

-- Views back up, least dependent first.
CREATE VIEW "REPORTING"."VW_PROJECT_BILLING_AGG" AS
 SELECT p."TENANT_ID",
    p."ID" AS "PROJECT_ID",
    COALESCE(pp_agg."ADVANCE_INVOICE_NET_TOTAL", 0::numeric) AS "ADVANCE_INVOICE_NET_TOTAL",
    COALESCE(i_agg."INVOICE_NET_TOTAL", 0::numeric) AS "INVOICE_NET_TOTAL",
    COALESCE(pay_agg."PAYED_NET_TOTAL", 0::numeric) AS "PAYED_NET_TOTAL"
   FROM "PROJECT" p
     LEFT JOIN ( SELECT "ADVANCE_INVOICE"."TENANT_ID",
            "ADVANCE_INVOICE"."PROJECT_ID",
            sum(COALESCE("ADVANCE_INVOICE"."TOTAL_AMOUNT_NET", 0::numeric)) AS "ADVANCE_INVOICE_NET_TOTAL"
           FROM "ADVANCE_INVOICE"
          GROUP BY "ADVANCE_INVOICE"."TENANT_ID", "ADVANCE_INVOICE"."PROJECT_ID") pp_agg ON pp_agg."TENANT_ID" = p."TENANT_ID" AND pp_agg."PROJECT_ID" = p."ID"
     LEFT JOIN ( SELECT "INVOICE"."TENANT_ID",
            "INVOICE"."PROJECT_ID",
            sum(COALESCE("INVOICE"."TOTAL_AMOUNT_NET", 0::numeric)) AS "INVOICE_NET_TOTAL"
           FROM "INVOICE"
          GROUP BY "INVOICE"."TENANT_ID", "INVOICE"."PROJECT_ID") i_agg ON i_agg."TENANT_ID" = p."TENANT_ID" AND i_agg."PROJECT_ID" = p."ID"
     LEFT JOIN ( SELECT "PAYMENT"."TENANT_ID",
            "PAYMENT"."PROJECT_ID",
            sum(COALESCE("PAYMENT"."AMOUNT_PAYED_NET", 0::numeric)) AS "PAYED_NET_TOTAL"
           FROM "PAYMENT"
          GROUP BY "PAYMENT"."TENANT_ID", "PAYMENT"."PROJECT_ID") pay_agg ON pay_agg."TENANT_ID" = p."TENANT_ID" AND pay_agg."PROJECT_ID" = p."ID";

CREATE VIEW "public"."VW_REPORT_PROJECT_DETAIL" AS
 SELECT p."TENANT_ID",
    p."ID" AS "PROJECT_ID",
    p."NAME_LONG",
    p."NAME_SHORT",
    p."PROJECT_STATUS_ID",
    ps_lkp."NAME_SHORT" AS "PROJECT_STATUS_NAME_SHORT",
    p."PROJECT_TYPE_ID",
    pt."NAME_SHORT" AS "PROJECT_TYPE_NAME_SHORT",
    p."PROJECT_MANAGER_ID",
    e."ABBR"::text ||
        CASE
            WHEN e."FIRST_NAME" IS NOT NULL THEN ((': '::text || e."FIRST_NAME"::text) || ' '::text) || COALESCE(e."LAST_NAME", ''::character varying)::text
            ELSE ''::text
        END AS "PROJECT_MANAGER_DISPLAY",
    p."ADDRESS_ID",
    a."ADDRESS_NAME_1" AS "ADDRESS_NAME",
    p."COMPANY_ID",
    c."COMPANY_NAME_1" AS "COMPANY_NAME",
    p."DEPARTMENT_ID",
    d."NAME_SHORT" AS "DEPARTMENT_NAME",
    p."CONTACT_ID",
    co."LAST_NAME" AS "CONTACT_NAME",
    p.created_at AS "PROJECT_created_at",
    COALESCE(pa."REVENUE_BUDGET", 0::numeric) + COALESCE(pa."EXTRAS_BUDGET", 0::numeric) AS "BUDGET_TOTAL_NET",
    pa."LEISTUNGSSTAND_PERCENT",
    COALESCE(pa."REVENUE_COMPLETION_VALUE", 0::numeric) + COALESCE(pa."EXTRAS_COMPLETION_VALUE", 0::numeric) AS "LEISTUNGSSTAND_VALUE",
    COALESCE(ta."HOURS_TOTAL", 0::numeric) AS "HOURS_TOTAL",
    COALESCE(ta."COST_TOTAL", 0::numeric) AS "COST_TOTAL",
    COALESCE(pa."REVENUE_COMPLETION_VALUE", 0::numeric) + COALESCE(pa."EXTRAS_COMPLETION_VALUE", 0::numeric) AS "EARNED_VALUE_NET",
        CASE
            WHEN (COALESCE(pa."REVENUE_COMPLETION_VALUE", 0::numeric) + COALESCE(pa."EXTRAS_COMPLETION_VALUE", 0::numeric)) = 0::numeric THEN NULL::numeric
            ELSE COALESCE(ta."COST_TOTAL", 0::numeric) / (COALESCE(pa."REVENUE_COMPLETION_VALUE", 0::numeric) + COALESCE(pa."EXTRAS_COMPLETION_VALUE", 0::numeric))
        END AS "COST_RATIO",
    COALESCE(pa."REVENUE_BUDGET", 0::numeric) + COALESCE(pa."EXTRAS_BUDGET", 0::numeric) - (COALESCE(pa."REVENUE_COMPLETION_VALUE", 0::numeric) + COALESCE(pa."EXTRAS_COMPLETION_VALUE", 0::numeric)) AS "REMAINING_BUDGET_NET",
    COALESCE(p."ADVANCE_INVOICED", 0::numeric) AS "ADVANCE_INVOICE_NET_TOTAL",
    COALESCE(p."INVOICED", 0::numeric) AS "INVOICE_NET_TOTAL",
    COALESCE(ba."PAYED_NET_TOTAL", 0::numeric) AS "PAYED_NET_TOTAL",
    COALESCE(p."ADVANCE_INVOICED", 0::numeric) + COALESCE(p."INVOICED", 0::numeric) AS "BILLED_NET_TOTAL",
    COALESCE(pa."REVENUE_COMPLETION_VALUE", 0::numeric) + COALESCE(pa."EXTRAS_COMPLETION_VALUE", 0::numeric) - (COALESCE(p."ADVANCE_INVOICED", 0::numeric) + COALESCE(p."INVOICED", 0::numeric)) AS "OPEN_NET_TOTAL",
    COALESCE(ta."SALES_TOTAL", 0::numeric) AS "SALES_TOTAL",
    COALESCE(ta."QTY_EXT_TOTAL", 0::numeric) AS "QTY_EXT_TOTAL"
   FROM "PROJECT" p
     LEFT JOIN "REPORTING"."VW_PROJECT_PROGRESS_AGG" pa ON pa."TENANT_ID" = p."TENANT_ID" AND pa."PROJECT_ID" = p."ID"
     LEFT JOIN "REPORTING"."VW_PROJECT_TIME_AGG" ta ON ta."TENANT_ID" = p."TENANT_ID" AND ta."PROJECT_ID" = p."ID"
     LEFT JOIN "REPORTING"."VW_PROJECT_BILLING_AGG" ba ON ba."TENANT_ID" = p."TENANT_ID" AND ba."PROJECT_ID" = p."ID"
     LEFT JOIN "EMPLOYEE" e ON e."TENANT_ID" = p."TENANT_ID" AND e."ID" = p."PROJECT_MANAGER_ID"
     LEFT JOIN "PROJECT_STATUS" ps_lkp ON ps_lkp."ID" = p."PROJECT_STATUS_ID"
     LEFT JOIN "PROJECT_TYPE" pt ON pt."ID" = p."PROJECT_TYPE_ID"
     LEFT JOIN "ADDRESS" a ON a."TENANT_ID" = p."TENANT_ID" AND a."ID" = p."ADDRESS_ID"
     LEFT JOIN "COMPANY" c ON c."TENANT_ID" = p."TENANT_ID" AND c."ID" = p."COMPANY_ID"
     LEFT JOIN "DEPARTMENT" d ON d."ID" = p."DEPARTMENT_ID"
     LEFT JOIN "CONTACTS" co ON co."TENANT_ID" = p."TENANT_ID" AND co."ID" = p."CONTACT_ID";

CREATE VIEW "public"."VW_REPORT_PROJECT_LIST_ROOT" AS
 SELECT "TENANT_ID",
    "PROJECT_ID",
    "NAME_SHORT",
    "NAME_LONG",
    "PROJECT_STATUS_ID",
    "PROJECT_STATUS_NAME_SHORT",
    "PROJECT_TYPE_ID",
    "PROJECT_TYPE_NAME_SHORT",
    "PROJECT_MANAGER_ID",
    "PROJECT_MANAGER_DISPLAY",
    "ADDRESS_ID",
    "ADDRESS_NAME",
    "COMPANY_ID",
    "COMPANY_NAME",
    "DEPARTMENT_ID",
    "DEPARTMENT_NAME",
    "CONTACT_ID",
    "CONTACT_NAME",
    "BUDGET_TOTAL_NET",
    "LEISTUNGSSTAND_PERCENT",
    "LEISTUNGSSTAND_VALUE",
    "HOURS_TOTAL",
    "COST_TOTAL",
    "EARNED_VALUE_NET",
    "COST_RATIO",
    "REMAINING_BUDGET_NET",
    "ADVANCE_INVOICE_NET_TOTAL",
    "INVOICE_NET_TOTAL",
    "PAYED_NET_TOTAL",
    "BILLED_NET_TOTAL",
    "OPEN_NET_TOTAL"
   FROM "VW_REPORT_PROJECT_DETAIL" pd;

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
