-- 0152_06_booking.sql
-- Generated by backend/scripts/rename/rename.js - do not hand-edit.
-- Source of truth: backend/scripts/rename/rename-map.json
-- migrate.js wraps this file in a transaction; a failure rolls the whole file back.

-- block 06-booking
ALTER TABLE "ARBZG_AUDIT" RENAME COLUMN "DATE_VOUCHER" TO "BOOKING_DATE";
ALTER TABLE "ARBZG_AUDIT" RENAME COLUMN "TEC_ID" TO "BOOKING_ID";
ALTER TABLE "TEC" RENAME COLUMN "DATE_VOUCHER" TO "BOOKING_DATE";
ALTER TABLE "TEC" RENAME TO "BOOKING";
ALTER TABLE "TEC_REBOOKING" RENAME COLUMN "DATE_VOUCHER" TO "BOOKING_DATE";
ALTER TABLE "TEC_REBOOKING" RENAME COLUMN "TEC_ID" TO "BOOKING_ID";
ALTER TABLE "TEC_REBOOKING" RENAME TO "BOOKING_REBOOKING";

-- PostgREST serves from a cached schema; without this it keeps using the old one.
NOTIFY pgrst, 'reload schema';
