-- ============================================================================
-- 0181_gesamtprojekt.sql — Gesamtprojekte (mehrere Projekte als eine Einheit)
--
-- WARUM
--   Ein Vorhaben besteht in Planungsbueros oft aus mehreren Einzelvertraegen:
--   Stufenvertraege (LPH 1–4, dann 5–8), Nachtraege als eigener Vertrag,
--   Teilleistungen an einen anderen Rechnungsempfaenger. Jeder davon ist in
--   plan&simple ein eigenes Projekt — ausgewertet werden soll aber auch das
--   Vorhaben als Ganzes.
--
--   Mehrere Vertraege je Projekt waeren der andere Weg; der haette Struktur,
--   Rechnungen, Schlussrechnungs-Abzuege, offenen Betrag, E-Rechnung und den
--   Report „Teilfertige Leistungen" nach Vertrag aufspalten muessen. Das
--   Gesamtprojekt ist deshalb nur eine KLAMMER: Buchungen, Vertrag, Rechnungen
--   und Leistungsstaende bleiben am einzelnen Projekt, das Gesamtprojekt
--   summiert und ordnet ein. Konzept: docs/GESAMTPROJEKT_CONCEPT.md
--
-- FORM
--   Flach: ein Projekt gehoert zu hoechstens einem Gesamtprojekt, eine Ebene.
--   Damit ist jede Summe eindeutig — ein Projekt kann nicht in zwei Summen
--   zugleich stecken.
--
-- KEINE UNIQUE-REGEL auf NAME/ABBR: beide vergibt der Mandant selbst, eine
--   Regel ohne TENANT_ID wuerde fremde Bueros aussperren und verraten (0164).
--   Bei gleichem Namen fragt die Oberflaeche nach.
--
-- LOESCHEN
--   ADDRESS_ID/MANAGER_ID sind reine Angaben — ein geloeschter Auftraggeber
--   oder Mitarbeiter leert sie, statt das Loeschen zu blockieren.
--   PROJECT.PROJECT_GROUP_ID faellt beim Loeschen des Gesamtprojekts auf
--   NULL; die Projekte bleiben. (Der Service leert die Zuordnung vorher
--   ausdruecklich, die Regel hier ist das Netz darunter.)
--
-- MANDANTENTRENNUNG
--   TENANT_ID mit DEFAULT current_tenant_id() plus Policy tenant_isolation
--   (Muster wie 0137/0177). Reines DDL, kein Claim noetig. Der Fremdschluessel
--   PROJECT → PROJECT_GROUP prueft den Mandanten NICHT — das tut
--   assertOwnGroup in services/gesamtprojekte.js.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."PROJECT_GROUP" (
  "ID"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TENANT_ID"   bigint NOT NULL DEFAULT public.current_tenant_id(),
  "ABBR"        text,
  "NAME"        text   NOT NULL,
  "ADDRESS_ID"  bigint REFERENCES public."ADDRESS"("ID")  ON DELETE SET NULL,
  "MANAGER_ID"  bigint REFERENCES public."EMPLOYEE"("ID") ON DELETE SET NULL,
  "NOTES"       text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_project_group_name CHECK (length(btrim("NAME")) > 0)
);

COMMENT ON TABLE public."PROJECT_GROUP" IS
  'Gesamtprojekt: Klammer um mehrere Projekte (Einzelvertraege) eines Vorhabens. Traegt keine Belege — summiert nur.';

CREATE INDEX IF NOT EXISTS idx_project_group_tenant
  ON public."PROJECT_GROUP" ("TENANT_ID");

ALTER TABLE public."PROJECT"
  ADD COLUMN IF NOT EXISTS "PROJECT_GROUP_ID" bigint
  REFERENCES public."PROJECT_GROUP"("ID") ON DELETE SET NULL;

COMMENT ON COLUMN public."PROJECT"."PROJECT_GROUP_ID" IS
  'Gesamtprojekt, zu dem dieses Projekt gehoert (hoechstens eins). Projekt kopieren uebernimmt die Zuordnung.';

CREATE INDEX IF NOT EXISTS idx_project_project_group
  ON public."PROJECT" ("PROJECT_GROUP_ID") WHERE "PROJECT_GROUP_ID" IS NOT NULL;

-- ── Mandantentrennung in der Datenbank ──────────────────────────────────────
ALTER TABLE public."PROJECT_GROUP" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PROJECT_GROUP" FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON public."PROJECT_GROUP";
CREATE POLICY tenant_isolation ON public."PROJECT_GROUP" FOR ALL
  USING      ("TENANT_ID" = public.current_tenant_id() OR public.is_system_request())
  WITH CHECK ("TENANT_ID" = public.current_tenant_id() OR public.is_system_request());

-- PostgREST-Rollen explizit berechtigen (siehe 0137).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plain_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."PROJECT_GROUP" TO plain_app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plain_system') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."PROJECT_GROUP" TO plain_system;
  END IF;
END $$;
