-- ============================================================================
-- 0184_dokument_textbausteine.sql — Textbausteine fuer Belege
--
-- WARUM
--   Je Belegart gab es genau einen Kopf- und einen Fusstext (TEXT_TEMPLATE).
--   Bueros brauchen aber wechselnde Texte: „Abschlag nach Zahlungsplan",
--   „Schlussrechnung mit Gewaehrleistungshinweis", ein Hinweis fuer
--   oeffentliche Auftraggeber. Die Bibliothek haelt beliebig viele benannte
--   Texte; der Standard bleibt TEXT_TEMPLATE, die Bausteine sind Alternativen,
--   die man im Rechnungsassistenten waehlt (services/documentTexts.js).
--
-- FORM
--   CATEGORY: Belegkategorie aus services/documentLayout.js, NULL = alle.
--   POSITION: intro (Kopftext), closing (Fusstext), free (eigener Textblock).
--   Keine UNIQUE-Regel auf LABEL — der Mandant vergibt es selbst (0164).
--
-- MANDANTENTRENNUNG
--   TENANT_ID mit DEFAULT current_tenant_id() plus Policy tenant_isolation
--   (Muster wie 0181). Reines DDL, kein Claim noetig.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."DOCUMENT_TEXT_SNIPPET" (
  "ID"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TENANT_ID"   bigint NOT NULL DEFAULT public.current_tenant_id(),
  "CATEGORY"    text,
  "POSITION"    text   NOT NULL DEFAULT 'free',
  "LABEL"       text   NOT NULL,
  "TEXT"        text   NOT NULL,
  "SORT_ORDER"  integer NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_doc_text_position CHECK ("POSITION" IN ('intro', 'closing', 'free')),
  CONSTRAINT chk_doc_text_label    CHECK (length(btrim("LABEL")) > 0)
);

COMMENT ON TABLE public."DOCUMENT_TEXT_SNIPPET" IS
  'Textbausteine fuer Belege (Kopf-, Fusstext, eigene Textbloecke) — Alternativen zum Standardtext in TEXT_TEMPLATE.';

CREATE INDEX IF NOT EXISTS idx_doc_text_snippet_tenant
  ON public."DOCUMENT_TEXT_SNIPPET" ("TENANT_ID", "CATEGORY");

-- ── Mandantentrennung in der Datenbank ──────────────────────────────────────
ALTER TABLE public."DOCUMENT_TEXT_SNIPPET" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DOCUMENT_TEXT_SNIPPET" FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON public."DOCUMENT_TEXT_SNIPPET";
CREATE POLICY tenant_isolation ON public."DOCUMENT_TEXT_SNIPPET" FOR ALL
  USING      ("TENANT_ID" = public.current_tenant_id() OR public.is_system_request())
  WITH CHECK ("TENANT_ID" = public.current_tenant_id() OR public.is_system_request());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plain_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."DOCUMENT_TEXT_SNIPPET" TO plain_app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plain_system') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."DOCUMENT_TEXT_SNIPPET" TO plain_system;
  END IF;
END $$;
